# Site settings
# in the templates available like {{ site.myvariable }}.
title: 성장하는 과정
subtitle: 혠로그 since 2022.12  
email: leehin5874@naver.com
brand: 혜니의 공부 발자취
headline: 하루하루 담아보는 기록
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leehin5874.github.io" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: leehin5874@naver.com
phone: +82 10-4486-5874

# Tracking
googleAnalitycsID: UA-83933844-1

